/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as carousel_carouselConfig from "../carousel/carouselConfig.js";
import type * as carousels from "../carousels.js";
import type * as helpers_asyncMap from "../helpers/asyncMap.js";
import type * as imageMessages from "../imageMessages.js";
import type * as messages_listImageDescriptions from "../messages/listImageDescriptions.js";
import type * as messages_listWithContent from "../messages/listWithContent.js";
import type * as messages from "../messages.js";
import type * as openai from "../openai.js";
import type * as openai_functions_runServerFunction from "../openai_functions/runServerFunction.js";
import type * as slides from "../slides.js";
import type * as textMessages from "../textMessages.js";
import type * as validators_carousels from "../validators/carousels.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "carousel/carouselConfig": typeof carousel_carouselConfig;
  carousels: typeof carousels;
  "helpers/asyncMap": typeof helpers_asyncMap;
  imageMessages: typeof imageMessages;
  "messages/listImageDescriptions": typeof messages_listImageDescriptions;
  "messages/listWithContent": typeof messages_listWithContent;
  messages: typeof messages;
  openai: typeof openai;
  "openai_functions/runServerFunction": typeof openai_functions_runServerFunction;
  slides: typeof slides;
  textMessages: typeof textMessages;
  "validators/carousels": typeof validators_carousels;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
